#!/bin/bash

usage() {

cat <<-EOF
    Usage: $0 [command] [options]
    Commands:
    up  - Creates the application container from the built images
            When using the '--logs' option, use ctrl-c to exit logging. Use "down" or "stop" to stop the run.
            Examples:
            $0 start
            $0 start --logs
            $0 start --wait --logs
    start - Same as up
    stop - Stops the services.  This is a non-destructive process.  The volumes and containers
            are not deleted so they will be reused the next time you run start.
EOF
exit 1
}

function build() {
    docker build -t tendermint-load-test .
    
    cd tendermint
    ./gen-network-config.sh
    docker-compose -f ./docker-compose.yml up -d

    cd ..
}

function rebuild() {
    cd tendermint

    docker-compose down
    ./gen-network-config.sh
    docker-compose -f ./docker-compose.yml up -d

    cd ..
}

function start() {
    # rate: time: size:
    read -p "Test name: " TEST
    read -p "Transaction rate: " RATE
    read -p "Time limit: " TIME
    read -p "Size: " SIZE
    read -p "Transaciton type: " TXN_TYPE

    if [ -z $RATE ]
    then
        RATE=1000
    fi

    if [ -z $TIME ]
    then 
        TIME=10
    fi

    if [ -z $SIZE ]
    then
        SIZE=250
    fi

    if [ -z $TXN_TYPE ]
    then
        TXN_TYPE="async"
    fi

    if [ -z $TEST ]
    then
        TEST="default"
    fi
    mkdir -p tests
    mkdir -p tests/$TEST

    echo "Starting coordinator with rate: $RATE time: $TIME size: $SIZE"

    h1=$(curl "http://0.0.0.0:26657/abci_info?" | jq .result.response.last_block_height |  tr -d '"')
    h1=$((h1+3))
    ./build/tm-load-test \
    coordinator \
    --expect-workers 2 \
    --bind localhost:26670 \
    -c 1 -T $TIME -r $RATE -s $SIZE \
    --broadcast-tx-method $TXN_TYPE \
    --endpoints ws://0.0.0.0:26657/websocket,ws://0.0.0.0:26757/websocket,ws://0.0.0.0:26857/websocket,ws://0.0.0.0:26957/websocket,ws://0.0.0.0:27057/websocket,ws://0.0.0.0:27157/websocket,ws://0.0.0.0:27257/websocket,ws://0.0.0.0:27357/websocket,ws://0.0.0.0:27457/websocket,ws://0.0.0.0:27557/websocket,ws://0.0.0.0:27657/websocket \
    --endpoint-select-method any \
    --stats-output ./tests/$TEST/"$RATE:$TIME:$SIZE".csv &

    echo "Starting worker 1"
    start_worker &

    echo "Starting worker 2"
    start_worker

    wait

    h2=$(curl "http://0.0.0.0:26657/abci_info?" | jq .result.response.last_block_height | tr -d '"')
    h2=$((h2+3))
    echo $h1 $h2

    txns=$(calculate_throughput $h1 $h2)
    throughput=$((txns/TIME))
    # echo $throughput
    echo "Final throughput: $throughput" >> "./tests/$TEST/"$RATE:$TIME:$SIZE".csv"
}

function start_worker() {
    ./build/tm-load-test worker
}

function calculate_throughput() {
    h1=$1
    h2=$2
    count=0
    for((i=h1;i<=h2;i++)) {
        data=$(curl "http://0.0.0.0:26657/block?height=$i" | jq .result.block.data.txs| tr -d '[]')
        readarray -d, -t -s 1 txs <<< "$data"
        n=${#txs[@]}
        count=$((count+n))        
    }
    echo $count
}

function stop() {
    cd tendermint
    docker-compose -f ./docker-compose.yml down 
    sudo rm -rf network-config
    cd ..
}

function down() {
    cd tendermint
    docker-compose -f ./docker-compose.yml down 
    sudo rm -rf network-config
    cd ..
    docker image rm tendermint-load-test:latest
}

# =================================================================================================================

COMMAND=$1

case "$COMMAND" in
    build)
    build
    ;;
    rebuild)
    rebuild
    ;;
    start | up)
    start
    ;;
    stop)
    stop
    ;;
    down)
    down
    ;;
    *)
    usage
    ;;
esac

