version: '3.7'

networks:
  localnet:
services:
  validator-0:
    networks:
    - localnet
    image: ${TENDERMINT_IMAGE}:${TENDERMINT_VERSION}
    ports:
      - 26656:26656    # Tendermint peer-to-peer (P2P) port
      - 26657:26657    # Tendermint RPC port
      - 26660:26660    # Prometheus metrics port
      - 1317:1317      # Cosmos REST API port
      - 9090:9090      # gRPC port
      - 9091:9091      # gRPC-Gateway port
    command: checkersd start --x-crisis-skip-assert-invariants
    volumes:
      - ./network-config/validator-0/config:/root/.checkers/config
      - ./network-config/validator-0/data:/root/.checkers/data
      - ./network-config/seeds.txt:/root/.checkers/config/seeds.txt 
  validator-1:
    networks:
    - localnet
    image: ${TENDERMINT_IMAGE}:${TENDERMINT_VERSION}
    ports:
      - 26756:26656    # Tendermint peer-to-peer (P2P) port
      - 26757:26657    # Tendermint RPC port
      - 26760:26660    # Prometheus metrics port
      - 1417:1317      # Cosmos REST API port
      - 9190:9090      # gRPC port
      - 9191:9091      # gRPC-Gateway port      
    command: checkersd start --x-crisis-skip-assert-invariants
    volumes:
      - ./network-config/validator-1/config:/root/.checkers/config
      - ./network-config/validator-1/data:/root/.checkers/data 
      - ./network-config/seeds.txt:/root/.checkers/config/seeds.txt     
  validator-2:
    networks:
    - localnet
    image: ${TENDERMINT_IMAGE}:${TENDERMINT_VERSION}
    ports:
      - 26856:26656    # Tendermint peer-to-peer (P2P) port
      - 26857:26657    # Tendermint RPC port
      - 26860:26660    # Prometheus metrics port
      - 1517:1317      # Cosmos REST API port
      - 9290:9090      # gRPC port
      - 9291:9091      # gRPC-Gateway port      
    command: checkersd start --x-crisis-skip-assert-invariants
    volumes:
      - ./network-config/validator-2/config:/root/.checkers/config
      - ./network-config/validator-2/data:/root/.checkers/data
      - ./network-config/seeds.txt:/root/.checkers/config/seeds.txt 
  validator-3:
    networks:
    - localnet
    image: ${TENDERMINT_IMAGE}:${TENDERMINT_VERSION}
    ports:
      - 26956:26656    # Tendermint peer-to-peer (P2P) port
      - 26957:26657    # Tendermint RPC port
      - 26960:26660    # Prometheus metrics port
      - 1617:1317      # Cosmos REST API port
      - 9390:9090      # gRPC port
      - 9391:9091      # gRPC-Gateway port      
    command: checkersd start --x-crisis-skip-assert-invariants
    volumes:
      - ./network-config/validator-3/config:/root/.checkers/config
      - ./network-config/validator-3/data:/root/.checkers/data
      - ./network-config/seeds.txt:/root/.checkers/config/seeds.txt      
  seed-0:
    networks:
    - localnet
    image: ${TENDERMINT_IMAGE}:${TENDERMINT_VERSION}
    ports:
      - 27056:26656
      - 27057:26657
      - 27060:26660
      - 1717:1317      # Cosmos REST API port
      - 9490:9090      # gRPC port
      - 9491:9091      # gRPC-Gateway port  
    command: checkersd start    
    volumes:
      - ./network-config/seed-0/config:/root/.checkers/config
      - ./network-config/seed-0/data:/root/.checkers/data
      - ./network-config/seeds.txt:/root/.checkers/config/seeds.txt